package com.myspace.currencyrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CurrencyData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	//@org.kie.api.definition.type.Label(value = "Transaction Id")
	private java.lang.String transId;
	//@org.kie.api.definition.type.Label(value = "Currency Code")
	private java.lang.String currency;

	public CurrencyData() {
	}

	public java.lang.String getTransId() {
		return this.transId;
	}

	public void setTransId(java.lang.String transId) {
		this.transId = transId;
	}

	public java.lang.String getCurrency() {
		return this.currency;
	}

	public void setCurrency(java.lang.String currency) {
		this.currency = currency;
	}

	public CurrencyData(java.lang.String transId, java.lang.String currency) {
		this.transId = transId;
		this.currency = currency;
	}

}